version: '3.8'

services:
  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/akbae/ci-grpc:latest
    container_name: grpc-server
    ports:
      - "50051:50051"
      - "2112:2112"
    networks:
      - grpc-network

networks:
  grpc-network:
    external: true
